In [1]:
# Import numpy, pandas, matplotlib.plt and seaborn
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
import scipy as sp
import seaborn as sns
sns.set_theme(style="darkgrid")     # Set the format for diagrams

In [2]:
# Set the values for A, B and C
a, b, c = [21, 11, 4]

# Set the value for n
n=100*b

# Set the values for x and y
x = np.array([i for i in np.arange(n)])/b
y = pd.read_csv("y.csv", header=None)

In [3]:
x

array([0.00000000e+00, 9.09090909e-02, 1.81818182e-01, ...,
       9.97272727e+01, 9.98181818e+01, 9.99090909e+01])

In [4]:
x.shape, y.shape

((1100,), (1100, 1100))

In [5]:
y.head()

,0,1,2,3,4,5,6,7,8,9,...,1090,1091,1092,1093,1094,1095,1096,1097,1098,1099
0,-50.391514,-49.358456,-48.259283,-47.093994,-45.862589,-44.565068,-43.201432,-41.771679,-40.275812,-38.713828,...,40315.641544,40388.740717,40461.906006,40535.137411,40608.434932,40681.798568,40755.228321,40828.724188,40902.286172,40975.914271
1,150.928265,151.961322,153.060496,154.225785,155.457190,156.754711,158.118347,159.548099,161.043967,162.605951,...,40516.961322,40590.060496,40663.225785,40736.457190,40809.754711,40883.118347,40956.548099,41030.043967,41103.605951,41177.234050
2,-62.429863,-61.396805,-60.297631,-59.132342,-57.900937,-56.603416,-55.239780,-53.810028,-52.314160,-50.752177,...,40303.603195,40376.702369,40449.867658,40523.099063,40596.396584,40669.760220,40743.189972,40816.685840,40890.247823,40963.875922
3,-101.057434,-100.024376,-98.925203,-97.759914,-96.528509,-95.230988,-93.867352,-92.437600,-90.941732,-89.379748,...,40264.975624,40338.074797,40411.240086,40484.471491,40557.769012,40631.132648,40704.562400,40778.058268,40851.620252,40925.248351
4,-72.010636,-70.977579,-69.878405,-68.713116,-67.481711,-66.184190,-64.820554,-63.390802,-61.894934,-60.332950,...,40294.022421,40367.121595,40440.286884,40513.518289,40586.815810,40660.179446,40733.609198,40807.105066,40880.667050,40954.295149